const axios = require('axios');
const crypto = require('crypto');





const apiUrl = 'https://healthidsbx.abdm.gov.in/api/v2/registration/aadhaar/generateOtp';
const authToken = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBbFJiNVdDbThUbTlFSl9JZk85ejA2ajlvQ3Y1MXBLS0ZrbkdiX1RCdkswIn0.eyJleHAiOjE2OTk1Mzc0MTUsImlhdCI6MTY5OTUxNTgxNSwianRpIjoiMDkxYzNmMDctNGM4OS00ZjkwLTkxOGUtNDFmMzM5MTA4NTM1IiwiaXNzIjoiaHR0cHM6Ly9kZXYubmRobS5nb3YuaW4vYXV0aC9yZWFsbXMvY2VudHJhbC1yZWdpc3RyeSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiIzMjQ5NGU3Mi0wOTAwLTRiOTUtOTlmMS0zOTczZDY2ZTBjMjYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJTQlhfMDAxMzAwIiwic2Vzc2lvbl9zdGF0ZSI6ImUwM2EwNzkwLWM4ZjAtNDc3NS04MGI3LTNjNjFiMDdiODIwYyIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo5MDA3Il0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJoaXUiLCJvZmZsaW5lX2FjY2VzcyIsImhlYWx0aElkIiwiT0lEQyIsImhpcCJdfSwicmVzb3VyY2VfYWNjZXNzIjp7IlNCWF8wMDEzMDAiOnsicm9sZXMiOlsidW1hX3Byb3RlY3Rpb24iXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJjbGllbnRIb3N0IjoiMTAuMjMzLjY3LjIzMiIsImNsaWVudElkIjoiU0JYXzAwMTMwMCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LXNieF8wMDEzMDAiLCJjbGllbnRBZGRyZXNzIjoiMTAuMjMzLjY3LjIzMiJ9.hrERMMMVCFbk5XrNU8lVk4dS2aul7YLNyIsgCf9Pwl91X87YqyTLtx_5fZIUwBZGgkdVErtRHsw4btN7cvG5QUmbUdYgJIxKuJaoexvXzTh0h4mcXJHOxwdoBB8FNla_BX40Jo8iy4VxtBAUoGlESAAimHXQoWwaSg4AlY96prYyw2aDu9TbQEvt21yq_aaOCGsYeYh4332HppSPJH7xfpxPd9pSC8L615VgGNOF9QZuMmaIVtaujFs8teuCJDm8Delg12gKhFBmJeMQSXfMW8gM7A6jvyqttomwDLcg0ey2W-tR7_TbHZzzD8o5I_pyvvQlq_bg80wBodSkTihkVg";

const headers = {
  'Authorization': authToken,
  'Content-Type': 'application/json',
  'Host': 'healthidsbx.abdm.gov.in',
  'User-Agent': 'axios/0.21.4', 
  'Accept': '*/*',
  'Accept-Encoding': 'gzip, deflate, br',
  'Connection': 'keep-alive',
  'Accept-Language': 'en-US', 
};

const requestBody = {
	"aadhaar": "kiHQVUa78TpG+OHmzwhxZrkQo8l/NWyme//23NAzmazHrYmHvCHAlc5zpHJ3h7hb0ILEB/CMZF8aMSUmkeyakb6p9ngqtvNR5D3+Z0hADtXEXmObJ35Ea1QrACc7e5Rb9nHQEbSvq/5hUbdl3kofoszBIdw3DS75ZZCAA71+/VzpyxK7k6/A3pGCDqNeI9hYW7JodiBJlO6ibKH00roiFu9OguIttdZxUlDY4UdnuqAJUBPn7/b54JupFct7arl9Epq0K5iOecIOMio6ECt99IXv4V0tkvvdf95uyzQ9kynbvp0s8dJuwyTfrYOzZpvhVC2OIrPbUD6IPfOxSwrmo3BZ8SYivXfoxlzHB+IiCcvmvZdXsuNok88RuKlXXWxe7OmTT+VaxQiWDG2uscrHminnzZgA8IasGOANaJmaBoWQ8ykQ0vqwXlTXs4kirz/YXUGCI5y4Ml/KMtsyUFv9hLrXtQjaIVn09Szjv0PeKYXYfEhua6ZT5Q7P6LBKFWYLGnjlEdMVx5r7MLPuVXcRKNY8WhdYcxBEdIEV8jnWZIB0CiKsKi9rMeed6jQvOel0i2XWOjToLhmByVQNRamJVehmbJ1ObQrLkJIsH9GISGtSlmSkiCvrUngCthFyYLtvIvp8/dTcZHGhsy9t4m+PgKpuqIhyNbA3Wqkn12ZYzMY="
};
axios.post(apiUrl, requestBody, { headers })
  .then(response => {
    console.log('Response:', response.data);
  })
 .catch(error => {
    console.error('Error:', error.message);
  });
